### ISSUE TITLE
Red Space

### ISSUE THREAD

**Issue by flatlin-e** [AshPowell/monokai-one-dark-vivid-syntax#1]
Hello,

I came across a red highlight everytime I hit the spacebar.

Love this theme and let me know if you fixed this!

Thanks!

**Comment by AshPowell** [comment]
Hi @ImFern , 

This is there by design, it highlights trailing white-space. If the line has content after white-space then it will disappear.

![Trailing whitespace gif](http://i.giphy.com/l41YeVaGm1RAOoGQw.gif)

If I have time this weekend I'll try and write in a checkbox to turn the feature on or off.

Glad you like the theme, still a few tweaks to come when I have the spare time :)

Cheers

**Comment by flatlin-e** [comment]
Sorry to mention this! It takes time to adjust to changes of course. :)

After a few hours rocking this theme, I am actually in love with the red trailing space. Makes my code just a little more prettier!

Perhaps having the red block in search fields can be removed?
![image](https://zippy.gfycat.com/GrandioseInformalAmericanratsnake.gif)

**Comment by AshPowell** [comment]
Sorry I thought I'd replied to this already! Yep thats a good idea - will adjust soon as I can :)

**Comment by flatlin-e** [comment]
Looks like this is fixed! Thank you!
